config/routes.rb
AlgolintCom::Application.routes.draw do
  resources :user_compiles
  resources :image_configs
  resources :packages
  resources :containers
  resources :container_stacks
  resources :networks
  resources :compilers
  resources :languages

  resources :folders
  resources :likes
  resources :contents
  devise_for :users, :skip => [:sessions]
  as :user do
    get 'join' => 'devise/registrations#new', :as => :signin_user
    get 'login' => 'sessions#new', :as => :login_user
    post 'login' => 'sessions#create', :as => :user_session
    get 'logout' => 'sessions#destroy', :as => :logout_user
  end

  root :to => 'home#homepage'

  match "/admin" => "home#admin", :as => :admin
  match "/list-codes-for-template" => "home#list_codes", :as => :list_codes
  match "/list-users-for-admin" => "home#list_users", :as => :list_users
  match "/make-tempate/:id" => "home#make_template", :as => :make_template
  match "/set-tempate-cat/:id/(:cat)" => "home#set_template_cat", :as => :set_template_cat

  get "dropbox/auth_start"
  get "dropbox/auth_finish"
  
  match "/get-profile-url" => "home#get_profile_name", :as => :get_profile_name
  match "/how-to-use" => "home#how_to_use", :as => :how_to_use
  match "/cli" => "home#cli", :as => :cli
  match "/explore" => "home#explore", :as => :explore
  match "/check-profile-name-availabilty" => "home#check_profile_name_avail", :as => :check_profile_name_avail
  match "/save-profile-url" => "home#save_profile_url", :as => :save_profile_name
  match "/reuse-code/:file_Id" => "home#reuse_code", :as => :reuse_code
  match "/compile-code" => "home#compile_code", :as => :compile_code
  match "/set-user-config-editor" => "home#set_default_user_editor_setting", :as => :set_default_user_editor_setting
  match "/like-code/:code_id" => "home#like_code", :as => :like_code
  match "/complete-dropbox-integration" => "dropbox#complete_integration", :as => :comp_dropbox_integration  
  match "/sync-to-dropbox" => "dropbox#upload", :as => :sync_to_dropbox  
  match "/:uid" => "home#profile", :as => :profile
  match "/:uid/:file_name-:file_id" => "home#content_public", :as => :content_public
  

end

app/models/folder.rb
class Folder < ActiveRecord::Base
  attr_accessible :name, :parent_id, :user_id
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  layout "blank"
  before_filter :check_credential, :except => []
  respond_to :html, :json

  # GET /folders
  # GET /folders.json
  def index
    if(params[:uid].present?)
      user = User.find_by_unique_key(params[:uid])
      if(user.present?)
        @folders = Folder.find(:all, :conditions => ["user_id = ?", user.id])
      end
    else
      @folders = Folder.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @folders }
    end
  end

  # GET /folders/1
  # GET /folders/1.json
  def show
    @folder = Folder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @folder }
    end
  end

  # GET /folders/new
  # GET /folders/new.json
  def new
    @folder = Folder.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @folder }
    end
  end

  # GET /folders/1/edit
  def edit
    @folder = Folder.find(params[:id])
  end

  # POST /folders
  # POST /folders.json
  def create
    @folder = Folder.new(params[:folder])
    @folder.user_id = current_user.id
    respond_to do |format|
      if @folder.save
        format.html { redirect_to @folder, notice: 'Folder was successfully created.' }
        format.json { render json: @folder, status: :created, location: @folder }
      else
        format.html { render action: "new" }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /folders/1
  # PUT /folders/1.json
  def update
    @folder = Folder.find(params[:id])
    @folder.user_id = current_user.id
    respond_to do |format|
      if @folder.update_attributes(params[:folder])
        format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folders/1
  # DELETE /folders/1.json
  def destroy
    @folder = Folder.find(params[:id])
    @folder.destroy

    respond_to do |format|
      format.html { redirect_to folders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_form.html.erb
<%= form_for(@folder) do |f| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% @folder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.text_field :parent_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/folders/edit.html.erb
<h1>Editing folder</h1>

<%= render 'form' %>

<%= link_to 'Show', @folder %> |
<%= link_to 'Back', folders_path %>

app/views/folders/index.html.erb
<h1>Listing folders</h1>

<table>
  <tr>
    <th>Name</th>
    <th>User</th>
    <th>Parent</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @folders.each do |folder| %>
  <tr>
    <td><%= folder.name %></td>
    <td><%= folder.user_id %></td>
    <td><%= folder.parent_id %></td>
    <td><%= link_to 'Show', folder %></td>
    <td><%= link_to 'Edit', edit_folder_path(folder) %></td>
    <td><%= link_to 'Destroy', folder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Folder', new_folder_path %>

app/views/folders/new.html.erb
<h1>New folder</h1>

<%= render 'form' %>

<%= link_to 'Back', folders_path %>

app/views/folders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @folder.name %>
</p>

<p>
  <b>User:</b>
  <%= @folder.user_id %>
</p>

<p>
  <b>Parent:</b>
  <%= @folder.parent_id %>
</p>


<%= link_to 'Edit', edit_folder_path(@folder) %> |
<%= link_to 'Back', folders_path %>