config/routes.rb
AlgolintCom::Application.routes.draw do
  resources :user_compiles
  resources :image_configs
  resources :packages
  resources :containers
  resources :container_stacks
  resources :networks
  resources :compilers
  resources :languages

  resources :folders
  resources :likes
  resources :contents
  devise_for :users, :skip => [:sessions]
  as :user do
    get 'join' => 'devise/registrations#new', :as => :signin_user
    get 'login' => 'sessions#new', :as => :login_user
    post 'login' => 'sessions#create', :as => :user_session
    get 'logout' => 'sessions#destroy', :as => :logout_user
  end

  root :to => 'home#homepage'

  match "/admin" => "home#admin", :as => :admin
  match "/list-codes-for-template" => "home#list_codes", :as => :list_codes
  match "/list-users-for-admin" => "home#list_users", :as => :list_users
  match "/make-tempate/:id" => "home#make_template", :as => :make_template
  match "/set-tempate-cat/:id/(:cat)" => "home#set_template_cat", :as => :set_template_cat

  get "dropbox/auth_start"
  get "dropbox/auth_finish"
  
  match "/get-profile-url" => "home#get_profile_name", :as => :get_profile_name
  match "/how-to-use" => "home#how_to_use", :as => :how_to_use
  match "/cli" => "home#cli", :as => :cli
  match "/explore" => "home#explore", :as => :explore
  match "/check-profile-name-availabilty" => "home#check_profile_name_avail", :as => :check_profile_name_avail
  match "/save-profile-url" => "home#save_profile_url", :as => :save_profile_name
  match "/reuse-code/:file_Id" => "home#reuse_code", :as => :reuse_code
  match "/compile-code" => "home#compile_code", :as => :compile_code
  match "/set-user-config-editor" => "home#set_default_user_editor_setting", :as => :set_default_user_editor_setting
  match "/like-code/:code_id" => "home#like_code", :as => :like_code
  match "/complete-dropbox-integration" => "dropbox#complete_integration", :as => :comp_dropbox_integration  
  match "/sync-to-dropbox" => "dropbox#upload", :as => :sync_to_dropbox  
  match "/:uid" => "home#profile", :as => :profile
  match "/:uid/:file_name-:file_id" => "home#content_public", :as => :content_public
  

end

app/models/container_stack.rb
class ContainerStack < ActiveRecord::Base
  attr_accessible :compiler_id, :count, :created_by, :dependency, :image_id, :image_type, :language_id, :name, :status

  IMAGE_TYPE_COMPILER = 0
  IMAGE_TYPE_CUSTOM = 10

  IMAGE_TYPE_NAMES = {
    IMAGE_TYPE_COMPILER => "Compiler",
    IMAGE_TYPE_CUSTOM => "Custom"
  }

  STATUS_STOPPED = 0
  STATUS_RUNNING = 1
  STATUS_ERROR = 2

  STATUS_NAMES = {
    STATUS_STOPPED => "Stopped",
    STATUS_RUNNING => "Running",
    STATUS_ERROR => "Error"
  }
  
end

app/controllers/container_stacks_controller.rb
class ContainerStacksController < ApplicationController
  # GET /container_stacks
  # GET /container_stacks.json
  def index
    @container_stacks = ContainerStack.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @container_stacks }
    end
  end

  # GET /container_stacks/1
  # GET /container_stacks/1.json
  def show
    @container_stack = ContainerStack.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @container_stack }
    end
  end

  # GET /container_stacks/new
  # GET /container_stacks/new.json
  def new
    @container_stack = ContainerStack.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @container_stack }
    end
  end

  # GET /container_stacks/1/edit
  def edit
    @container_stack = ContainerStack.find(params[:id])
  end

  # POST /container_stacks
  # POST /container_stacks.json
  def create
    @container_stack = ContainerStack.new(params[:container_stack])

    respond_to do |format|
      if @container_stack.save
        format.html { redirect_to @container_stack, notice: 'Container stack was successfully created.' }
        format.json { render json: @container_stack, status: :created, location: @container_stack }
      else
        format.html { render action: "new" }
        format.json { render json: @container_stack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /container_stacks/1
  # PUT /container_stacks/1.json
  def update
    @container_stack = ContainerStack.find(params[:id])

    respond_to do |format|
      if @container_stack.update_attributes(params[:container_stack])
        format.html { redirect_to @container_stack, notice: 'Container stack was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @container_stack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /container_stacks/1
  # DELETE /container_stacks/1.json
  def destroy
    @container_stack = ContainerStack.find(params[:id])
    @container_stack.destroy

    respond_to do |format|
      format.html { redirect_to container_stacks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/container_stacks_helper.rb
module ContainerStacksHelper
end

app/views/container_stacks/_form.html.erb
<%= form_for(@container_stack) do |f| %>
  <% if @container_stack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@container_stack.errors.count, "error") %> prohibited this container_stack from being saved:</h2>

      <ul>
      <% @container_stack.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image_type %><br />
    <select name="container_stack[image_type]">
      <% ContainerStack::IMAGE_TYPE_NAMES.each do |key, value| %>
      <option value="<%= key %>"><%= value %></option>
      <% end %>
    </select>
  </div>
  <div class="field">
    <%= f.label :language_id %><br />
    <select name="container_stack[language_id]">
      <% language = Language.all
	 for lang in language
	 %>
      <option value="<%= lang.id %>"><%= lang.name %></option>
      <% end %>
    </select>
  </div>
  <div class="field">
    <%= f.label :compiler_id %><br />
    <select name="container_stack[compiler_id]">
      <% compiler = Compiler.all
	 for comp in compiler
	 %>
      <option value="<%= comp.id %>"><%= comp.name %></option>
      <% end %>
    </select>
  </div>
  <div class="field">
    <%= f.label :image_id %><br />
    <%= f.text_field :image_id %>
  </div>
  <div class="field">
    <%= f.label :count %><br />
    <%= f.text_field :count %>
  </div>
  <div class="field">
    <%= f.label :dependency %><br />
    <%= f.text_field :dependency %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <select name="container_stack[status]">
      <% ContainerStack::STATUS_NAMES.each do |key, value| %>
      <option value="<%= key %>"><%= value %></option>
      <% end %>
    </select>
  </div>
  <div class="field">
    <%= f.label :created_by %><br />
    <%= f.text_field :created_by, :value => "-1" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/container_stacks/edit.html.erb
<h1>Editing container_stack</h1>

<%= render 'form' %>

<%= link_to 'Show', @container_stack %> |
<%= link_to 'Back', container_stacks_path %>

app/views/container_stacks/index.html.erb
<h5>Listing container_stacks</h5>
<%
   lang = Language.all
   lang_hash = {}
   for l in lang
   lang_hash[l.id] = l
   end
   
   comp = Compiler.all
   comp_hash = {}
   for c in comp
   comp_hash[c.id] = c
   end
   %>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Image type</th>
    <th>Language</th>
    <th>Compiler</th>
    <th>Image</th>
    <th>Count</th>
    <th>Dependency</th>
    <th>Status</th>
    <th>Created by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @container_stacks.each do |container_stack| %>
  <tr>
    <td><%= container_stack.name %></td>
    <td><%= ContainerStack::IMAGE_TYPE_NAMES[container_stack.image_type] %></td>
    <td><%= lang_hash[container_stack.language_id].name %></td>
    <td><%= comp_hash[container_stack.compiler_id].name %></td>
    <td><%= container_stack.image_id %></td>
    <td><%= container_stack.count %></td>
    <td><%= container_stack.dependency %></td>
    <td><%= ContainerStack::STATUS_NAMES[container_stack.status] %></td>
    <td><%= (container_stack.created_by == -1)? "System" : "User" %></td>
    <td><%= link_to 'Show', container_stack %></td>
    <td><%= link_to 'Edit', edit_container_stack_path(container_stack) %></td>
    <td><%= link_to 'Destroy', container_stack, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Container stack', new_container_stack_path %>

app/views/container_stacks/new.html.erb
<h1>New container_stack</h1>

<%= render 'form' %>

<%= link_to 'Back', container_stacks_path %>

app/views/container_stacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @container_stack.name %>
</p>

<p>
  <b>Image type:</b>
  <%= @container_stack.image_type %>
</p>

<p>
  <b>Language:</b>
  <%= @container_stack.language_id %>
</p>

<p>
  <b>Compiler:</b>
  <%= @container_stack.compiler_id %>
</p>

<p>
  <b>Image:</b>
  <%= @container_stack.image_id %>
</p>

<p>
  <b>Count:</b>
  <%= @container_stack.count %>
</p>

<p>
  <b>Dependency:</b>
  <%= @container_stack.dependency %>
</p>

<p>
  <b>Status:</b>
  <%= @container_stack.status %>
</p>

<p>
  <b>Created by:</b>
  <%= @container_stack.created_by %>
</p>


<%= link_to 'Edit', edit_container_stack_path(@container_stack) %> |
<%= link_to 'Back', container_stacks_path %>