config/routes.rb
AlgolintCom::Application.routes.draw do
  resources :user_compiles
  resources :image_configs
  resources :packages
  resources :containers
  resources :container_stacks
  resources :networks
  resources :compilers
  resources :languages

  resources :folders
  resources :likes
  resources :contents
  devise_for :users, :skip => [:sessions]
  as :user do
    get 'join' => 'devise/registrations#new', :as => :signin_user
    get 'login' => 'sessions#new', :as => :login_user
    post 'login' => 'sessions#create', :as => :user_session
    get 'logout' => 'sessions#destroy', :as => :logout_user
  end

  root :to => 'home#homepage'

  match "/admin" => "home#admin", :as => :admin
  match "/list-codes-for-template" => "home#list_codes", :as => :list_codes
  match "/list-users-for-admin" => "home#list_users", :as => :list_users
  match "/make-tempate/:id" => "home#make_template", :as => :make_template
  match "/set-tempate-cat/:id/(:cat)" => "home#set_template_cat", :as => :set_template_cat

  get "dropbox/auth_start"
  get "dropbox/auth_finish"
  
  match "/get-profile-url" => "home#get_profile_name", :as => :get_profile_name
  match "/how-to-use" => "home#how_to_use", :as => :how_to_use
  match "/cli" => "home#cli", :as => :cli
  match "/explore" => "home#explore", :as => :explore
  match "/check-profile-name-availabilty" => "home#check_profile_name_avail", :as => :check_profile_name_avail
  match "/save-profile-url" => "home#save_profile_url", :as => :save_profile_name
  match "/reuse-code/:file_Id" => "home#reuse_code", :as => :reuse_code
  match "/compile-code" => "home#compile_code", :as => :compile_code
  match "/set-user-config-editor" => "home#set_default_user_editor_setting", :as => :set_default_user_editor_setting
  match "/like-code/:code_id" => "home#like_code", :as => :like_code
  match "/complete-dropbox-integration" => "dropbox#complete_integration", :as => :comp_dropbox_integration  
  match "/sync-to-dropbox" => "dropbox#upload", :as => :sync_to_dropbox  
  match "/:uid" => "home#profile", :as => :profile
  match "/:uid/:file_name-:file_id" => "home#content_public", :as => :content_public
  

end

app/models/container.rb
class Container < ActiveRecord::Base
  attr_accessible :assigned_to, :host, :image_id, :port, :stack_id, :status, :type
  
  STATUS_CREATED = 1
  STATUS_RESTARTING = 2
  STATUS_RUNNING = 3
  STATUS_PAUSHED = 4
  STATUS_EXITED = 5

  STATUS_NAMES = {
    STATUS_CREATED => "Created",
    STATUS_RESTARTING => "Restarting",
    STATUS_RUNNING => "Running",
    STATUS_PAUSHED => "Paushed",
    STATUS_EXITED => "Exited"
  }
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  # GET /containers
  # GET /containers.json
  def index
    @containers = Container.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @containers }
    end
  end

  # GET /containers/1
  # GET /containers/1.json
  def show
    @container = Container.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @container }
    end
  end

  # GET /containers/new
  # GET /containers/new.json
  def new
    @container = Container.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @container }
    end
  end

  # GET /containers/1/edit
  def edit
    @container = Container.find(params[:id])
  end

  # POST /containers
  # POST /containers.json
  def create
    @container = Container.new(params[:container])

    respond_to do |format|
      if @container.save
        format.html { redirect_to @container, notice: 'Container was successfully created.' }
        format.json { render json: @container, status: :created, location: @container }
      else
        format.html { render action: "new" }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /containers/1
  # PUT /containers/1.json
  def update
    @container = Container.find(params[:id])

    respond_to do |format|
      if @container.update_attributes(params[:container])
        format.html { redirect_to @container, notice: 'Container was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /containers/1
  # DELETE /containers/1.json
  def destroy
    @container = Container.find(params[:id])
    @container.destroy

    respond_to do |format|
      format.html { redirect_to containers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/views/containers/_form.html.erb
<%= form_for(@container) do |f| %>
  <% if @container.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@container.errors.count, "error") %> prohibited this container from being saved:</h2>

      <ul>
      <% @container.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :stack_id %><br />
    <%= f.text_field :stack_id %>
  </div>
  <div class="field">
    <%= f.label :host %><br />
    <%= f.text_field :host %>
  </div>
  <div class="field">
    <%= f.label :port %><br />
    <%= f.text_field :port %>
  </div>
  <div class="field">
    <%= f.label :image_id %><br />
    <%= f.text_field :image_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :assigned_to %><br />
    <%= f.text_field :assigned_to %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/containers/edit.html.erb
<h1>Editing container</h1>

<%= render 'form' %>

<%= link_to 'Show', @container %> |
<%= link_to 'Back', containers_path %>

app/views/containers/index.html.erb
<h5>Listing containers</h5>

<table class="table">
  <tr>
    <th>Type</th>
    <th>Stack</th>
    <th>Host</th>
    <th>Port</th>
    <th>Image</th>
    <th>Status</th>
    <th>Assigned to</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @containers.each do |container| %>
  <tr>
    <td><%= container.type %></td>
    <td><%= container.stack_id %></td>
    <td><%= container.host %></td>
    <td><%= container.port %></td>
    <td><%= container.image_id %></td>
    <td><%= container.status %></td>
    <td><%= container.assigned_to %></td>
    <td><%= link_to 'Show', container %></td>
    <td><%= link_to 'Edit', edit_container_path(container) %></td>
    <td><%= link_to 'Destroy', container, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Container', new_container_path %>

app/views/containers/new.html.erb
<h1>New container</h1>

<%= render 'form' %>

<%= link_to 'Back', containers_path %>

app/views/containers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @container.type %>
</p>

<p>
  <b>Stack:</b>
  <%= @container.stack_id %>
</p>

<p>
  <b>Host:</b>
  <%= @container.host %>
</p>

<p>
  <b>Port:</b>
  <%= @container.port %>
</p>

<p>
  <b>Image:</b>
  <%= @container.image_id %>
</p>

<p>
  <b>Status:</b>
  <%= @container.status %>
</p>

<p>
  <b>Assigned to:</b>
  <%= @container.assigned_to %>
</p>


<%= link_to 'Edit', edit_container_path(@container) %> |
<%= link_to 'Back', containers_path %>