config/routes.rb
AlgolintCom::Application.routes.draw do
  resources :user_compiles
  resources :image_configs
  resources :packages
  resources :containers
  resources :container_stacks
  resources :networks
  resources :compilers
  resources :languages

  resources :folders
  resources :likes
  resources :contents
  devise_for :users, :skip => [:sessions]
  as :user do
    get 'join' => 'devise/registrations#new', :as => :signin_user
    get 'login' => 'sessions#new', :as => :login_user
    post 'login' => 'sessions#create', :as => :user_session
    get 'logout' => 'sessions#destroy', :as => :logout_user
  end

  root :to => 'home#homepage'

  match "/admin" => "home#admin", :as => :admin
  match "/list-codes-for-template" => "home#list_codes", :as => :list_codes
  match "/list-users-for-admin" => "home#list_users", :as => :list_users
  match "/make-tempate/:id" => "home#make_template", :as => :make_template
  match "/set-tempate-cat/:id/(:cat)" => "home#set_template_cat", :as => :set_template_cat

  get "dropbox/auth_start"
  get "dropbox/auth_finish"
  
  match "/get-profile-url" => "home#get_profile_name", :as => :get_profile_name
  match "/how-to-use" => "home#how_to_use", :as => :how_to_use
  match "/cli" => "home#cli", :as => :cli
  match "/explore" => "home#explore", :as => :explore
  match "/check-profile-name-availabilty" => "home#check_profile_name_avail", :as => :check_profile_name_avail
  match "/save-profile-url" => "home#save_profile_url", :as => :save_profile_name
  match "/reuse-code/:file_Id" => "home#reuse_code", :as => :reuse_code
  match "/compile-code" => "home#compile_code", :as => :compile_code
  match "/set-user-config-editor" => "home#set_default_user_editor_setting", :as => :set_default_user_editor_setting
  match "/like-code/:code_id" => "home#like_code", :as => :like_code
  match "/complete-dropbox-integration" => "dropbox#complete_integration", :as => :comp_dropbox_integration  
  match "/sync-to-dropbox" => "dropbox#upload", :as => :sync_to_dropbox  
  match "/:uid" => "home#profile", :as => :profile
  match "/:uid/:file_name-:file_id" => "home#content_public", :as => :content_public
  

end

app/models/image_config.rb
class ImageConfig < ActiveRecord::Base
  attr_accessible :access_config, :default_port, :dockerfile, :image_id, :image_type, :startup_config
end

app/controllers/image_configs_controller.rb
class ImageConfigsController < ApplicationController
  # GET /image_configs
  # GET /image_configs.json
  def index
    @image_configs = ImageConfig.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @image_configs }
    end
  end

  # GET /image_configs/1
  # GET /image_configs/1.json
  def show
    @image_config = ImageConfig.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image_config }
    end
  end

  # GET /image_configs/new
  # GET /image_configs/new.json
  def new
    @image_config = ImageConfig.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image_config }
    end
  end

  # GET /image_configs/1/edit
  def edit
    @image_config = ImageConfig.find(params[:id])
  end

  # POST /image_configs
  # POST /image_configs.json
  def create
    @image_config = ImageConfig.new(params[:image_config])

    respond_to do |format|
      if @image_config.save
        format.html { redirect_to @image_config, notice: 'Image config was successfully created.' }
        format.json { render json: @image_config, status: :created, location: @image_config }
      else
        format.html { render action: "new" }
        format.json { render json: @image_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /image_configs/1
  # PUT /image_configs/1.json
  def update
    @image_config = ImageConfig.find(params[:id])

    respond_to do |format|
      if @image_config.update_attributes(params[:image_config])
        format.html { redirect_to @image_config, notice: 'Image config was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @image_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_configs/1
  # DELETE /image_configs/1.json
  def destroy
    @image_config = ImageConfig.find(params[:id])
    @image_config.destroy

    respond_to do |format|
      format.html { redirect_to image_configs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/image_configs_helper.rb
module ImageConfigsHelper
end

app/views/image_configs/_form.html.erb
<%= form_for(@image_config) do |f| %>
  <% if @image_config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image_config.errors.count, "error") %> prohibited this image_config from being saved:</h2>

      <ul>
      <% @image_config.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_type %><br />
    <%= f.text_field :image_type %>
  </div>
  <div class="field">
    <%= f.label :image_id %><br />
    <%= f.text_field :image_id %>
  </div>
  <div class="field">
    <%= f.label :dockerfile %><br />
    <%= f.text_field :dockerfile %>
  </div>
  <div class="field">
    <%= f.label :startup_config %><br />
    <%= f.text_field :startup_config %>
  </div>
  <div class="field">
    <%= f.label :access_config %><br />
    <%= f.text_field :access_config %>
  </div>
  <div class="field">
    <%= f.label :default_port %><br />
    <%= f.text_field :default_port %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/image_configs/edit.html.erb
<h1>Editing image_config</h1>

<%= render 'form' %>

<%= link_to 'Show', @image_config %> |
<%= link_to 'Back', image_configs_path %>

app/views/image_configs/index.html.erb
<h5>Listing image_configs</h5>

<table class="table">
  <tr>
    <th>Image type</th>
    <th>Image</th>
    <th>Dockerfile</th>
    <th>Startup config</th>
    <th>Access config</th>
    <th>Default port</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @image_configs.each do |image_config| %>
  <tr>
    <td><%= image_config.image_type %></td>
    <td><%= image_config.image_id %></td>
    <td><%= image_config.dockerfile %></td>
    <td><%= image_config.startup_config %></td>
    <td><%= image_config.access_config %></td>
    <td><%= image_config.default_port %></td>
    <td><%= link_to 'Show', image_config %></td>
    <td><%= link_to 'Edit', edit_image_config_path(image_config) %></td>
    <td><%= link_to 'Destroy', image_config, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Image config', new_image_config_path %>

app/views/image_configs/new.html.erb
<h1>New image_config</h1>

<%= render 'form' %>

<%= link_to 'Back', image_configs_path %>

app/views/image_configs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image type:</b>
  <%= @image_config.image_type %>
</p>

<p>
  <b>Image:</b>
  <%= @image_config.image_id %>
</p>

<p>
  <b>Dockerfile:</b>
  <%= @image_config.dockerfile %>
</p>

<p>
  <b>Startup config:</b>
  <%= @image_config.startup_config %>
</p>

<p>
  <b>Access config:</b>
  <%= @image_config.access_config %>
</p>

<p>
  <b>Default port:</b>
  <%= @image_config.default_port %>
</p>


<%= link_to 'Edit', edit_image_config_path(@image_config) %> |
<%= link_to 'Back', image_configs_path %>